/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#ae2f34',
        'on-primary': '#ffffff',
        'primary-container': '#ff6b6b',
        'on-primary-container': '#6d0010',
        'primary-fixed': '#ffdad8',
        'primary-fixed-dim': '#ffb3b0',
        'on-primary-fixed': '#410006',
        'on-primary-fixed-variant': '#8c1520',
        'inverse-primary': '#ffb3b0',
        secondary: '#785900',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdc003',
        'on-secondary-container': '#6c5000',
        'secondary-fixed': '#ffdf9e',
        'secondary-fixed-dim': '#fabd00',
        'on-secondary-fixed': '#261a00',
        'on-secondary-fixed-variant': '#5b4300',
        tertiary: '#506073',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8d9db2',
        'on-tertiary-container': '#253446',
        'tertiary-fixed': '#d4e4fb',
        'tertiary-fixed-dim': '#b8c8de',
        'on-tertiary-fixed': '#0d1d2d',
        'on-tertiary-fixed-variant': '#39485a',
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#584140',
        'surface-variant': '#e1e3e4',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'surface-tint': '#ae2f34',
        outline: '#8c706f',
        'outline-variant': '#e0bfbd',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Be Vietnam Pro', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
        accent: ['Titan One', 'cursive', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        margin: '32px',
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
