/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#ae2f34',
        'on-primary': '#ffffff',
        'primary-container': '#ff6b6b',
        'on-primary-container': '#6d0010',
        'primary-fixed': '#ffdad8',
        'primary-fixed-dim': '#ffb3b0',
        'on-primary-fixed': '#410006',
        'on-primary-fixed-variant': '#8c1520',
        secondary: '#785900',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdc003',
        'on-secondary-container': '#6c5000',
        'secondary-fixed': '#ffdf9e',
        'secondary-fixed-dim': '#fabd00',
        'on-secondary-fixed': '#261a00',
        tertiary: '#506073',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8d9db2',
        'tertiary-fixed': '#d4e4fb',
        'tertiary-fixed-dim': '#b8c8de',
        'on-tertiary-fixed': '#0d1d2d',
        'on-tertiary-fixed-variant': '#39485a',
        surface: '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#584140',
        'surface-variant': '#e1e3e4',
        'outline': '#8c706f',
        'outline-variant': '#e0bfbd',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Be Vietnam Pro', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
